# Autogenerated by devscripts/update-version.py

__version__ = '2023.09.28.curl_cffi'

RELEASE_GIT_HEAD = 'dceb1636482364eb99116c9d3ad2f3972fc5613e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
